// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhIi_ak3iVDcRMHZR18-0mcXdEkYtil3A',
    appId: '1:73343193734:web:e31f278b031aa3d3317707',
    messagingSenderId: '73343193734',
    projectId: 'steppulse-20026',
    authDomain: 'steppulse-20026.firebaseapp.com',
    storageBucket: 'steppulse-20026.firebasestorage.app',
    measurementId: 'G-3P2ERRGV1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCykiN8Ol3a6_R2foLOvJm_pkk93VDWPc',
    appId: '1:73343193734:android:626506440a115c8b317707',
    messagingSenderId: '73343193734',
    projectId: 'steppulse-20026',
    storageBucket: 'steppulse-20026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjOK0ZnYnGEKB22kAH_oglv-m3LCRk0U',
    appId: '1:73343193734:ios:4ba01a94abc714b3317707',
    messagingSenderId: '73343193734',
    projectId: 'steppulse-20026',
    storageBucket: 'steppulse-20026.firebasestorage.app',
    iosBundleId: 'com.example.steppluse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjOK0ZnYnGEKB22kAH_oglv-m3LCRk0U',
    appId: '1:73343193734:ios:4ba01a94abc714b3317707',
    messagingSenderId: '73343193734',
    projectId: 'steppulse-20026',
    storageBucket: 'steppulse-20026.firebasestorage.app',
    iosBundleId: 'com.example.steppluse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhIi_ak3iVDcRMHZR18-0mcXdEkYtil3A',
    appId: '1:73343193734:web:2cab20e648dace89317707',
    messagingSenderId: '73343193734',
    projectId: 'steppulse-20026',
    authDomain: 'steppulse-20026.firebaseapp.com',
    storageBucket: 'steppulse-20026.firebasestorage.app',
    measurementId: 'G-YCE1R9C57T',
  );
}
